<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-D9EVLA1" failures="1" tests="1" name="cucumber.TestNGTestRunner" time="16.619" errors="0" timestamp="2025-04-17T18:04:05 IST" skipped="0">
  <testcase classname="cucumber.TestNGTestRunner" name="runScenario" time="16.619">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at shreya.stepDefinations.StepDefinationImpl.message_displayed_confirmationPage(StepDefinationImpl.java:55)
at âœ½."THANKYOU FOR ORDER" message is displayed on ConfirmationPage(file:///C:/Users/OMKAR/eclipse-workspace/SeleniumFrameworkDesign/src/test/java/cucumber/SubmitOrder.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- cucumber.TestNGTestRunner -->
